apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: encsecrets.dganochenko.work
  labels:
    app: seks-operator
spec:
 group: dganochenko.work
 names:
   plural: encsecrets
   singular: encsecret
   kind: EncSecret
   shortNames:
   - seks
 scope: Namespaced
 versions:
   - name: v1alpha1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         description: "Secret with RSA-encrypted data."
         type: object
         properties:
           apiVersion:
             type: string
           kind:
             type: string
           metadata:
             type: object
           data:
             description: "RSA-encrypted data"
             format: byte
             type: string
           x-kubernetes-preserve-unknown-fields: true
           type:
             description: "Secret type"
             type: string
         required: ["data"]

