---
apiVersion: v1
kind: Namespace
metadata:
  name: seks-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seks-operator-sa
  namespace: seks-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seks-operator-role
rules:
  - apiGroups: ["dganochenko.work"]
    resources: ["encsecrets","encsecrets/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: [""]
    resources: ["namespaces", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seks-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seks-operator-role
subjects:
  - kind: ServiceAccount
    name: seks-operator-sa
    namespace: seks-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seks-operator
  namespace: seks-operator
  labels: &labels
    app: seks-operator
    component: operator
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata: 
      labels: *labels
    spec:
      serviceAccountName: seks-operator-sa
      containers:
      - name: operator
        image: docker.io/dganochenko/seks-operator:0.1.0
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        env:
        - name: "CLUSTER_DOMAIN"
          value: "cluster.local"
        - name: "DEBUG_MODE"
          value: "false"

